// GENERATED by tools/gen_flags.py - do not edit.
#pragma once
#include <pebble.h>
#include <string.h>

typedef struct { const char *code; uint32_t resource_id; } FlagEntry;

static const FlagEntry FLAG_TABLE[] = {
  { "ALG", RESOURCE_ID_FLAG_ALG },
  { "ARG", RESOURCE_ID_FLAG_ARG },
  { "AUS", RESOURCE_ID_FLAG_AUS },
  { "AUT", RESOURCE_ID_FLAG_AUT },
  { "BEL", RESOURCE_ID_FLAG_BEL },
  { "BIH", RESOURCE_ID_FLAG_BIH },
  { "BRA", RESOURCE_ID_FLAG_BRA },
  { "CAN", RESOURCE_ID_FLAG_CAN },
  { "CIV", RESOURCE_ID_FLAG_CIV },
  { "COD", RESOURCE_ID_FLAG_COD },
  { "COL", RESOURCE_ID_FLAG_COL },
  { "CPV", RESOURCE_ID_FLAG_CPV },
  { "CRO", RESOURCE_ID_FLAG_CRO },
  { "CUW", RESOURCE_ID_FLAG_CUW },
  { "CZE", RESOURCE_ID_FLAG_CZE },
  { "ECU", RESOURCE_ID_FLAG_ECU },
  { "EGY", RESOURCE_ID_FLAG_EGY },
  { "ENG", RESOURCE_ID_FLAG_ENG },
  { "ESP", RESOURCE_ID_FLAG_ESP },
  { "FRA", RESOURCE_ID_FLAG_FRA },
  { "GER", RESOURCE_ID_FLAG_GER },
  { "GHA", RESOURCE_ID_FLAG_GHA },
  { "HAI", RESOURCE_ID_FLAG_HAI },
  { "IRN", RESOURCE_ID_FLAG_IRN },
  { "IRQ", RESOURCE_ID_FLAG_IRQ },
  { "JOR", RESOURCE_ID_FLAG_JOR },
  { "JPN", RESOURCE_ID_FLAG_JPN },
  { "KOR", RESOURCE_ID_FLAG_KOR },
  { "KSA", RESOURCE_ID_FLAG_KSA },
  { "MAR", RESOURCE_ID_FLAG_MAR },
  { "MEX", RESOURCE_ID_FLAG_MEX },
  { "NED", RESOURCE_ID_FLAG_NED },
  { "NOR", RESOURCE_ID_FLAG_NOR },
  { "NZL", RESOURCE_ID_FLAG_NZL },
  { "PAN", RESOURCE_ID_FLAG_PAN },
  { "PAR", RESOURCE_ID_FLAG_PAR },
  { "POR", RESOURCE_ID_FLAG_POR },
  { "QAT", RESOURCE_ID_FLAG_QAT },
  { "RSA", RESOURCE_ID_FLAG_RSA },
  { "SCO", RESOURCE_ID_FLAG_SCO },
  { "SEN", RESOURCE_ID_FLAG_SEN },
  { "SUI", RESOURCE_ID_FLAG_SUI },
  { "SWE", RESOURCE_ID_FLAG_SWE },
  { "TUN", RESOURCE_ID_FLAG_TUN },
  { "TUR", RESOURCE_ID_FLAG_TUR },
  { "URU", RESOURCE_ID_FLAG_URU },
  { "USA", RESOURCE_ID_FLAG_USA },
  { "UZB", RESOURCE_ID_FLAG_UZB },
};

static inline uint32_t flag_resource_for_code(const char *code) {
  for (size_t i = 0; i < sizeof(FLAG_TABLE) / sizeof(FLAG_TABLE[0]); i++) {
    if (strncmp(code, FLAG_TABLE[i].code, 3) == 0) return FLAG_TABLE[i].resource_id;
  }
  return RESOURCE_ID_FLAG_TBD;
}
