// Regenerates src/pkjs/teams.js from the checked-in tools/worldcup.teams.json.
// Run: node tools/gen_teams.js
var fs = require('fs');
var path = require('path');
var parser = require('../src/pkjs/parser');

var teamsJson = JSON.parse(
    fs.readFileSync(path.join(__dirname, 'worldcup.teams.json'), 'utf8'));
var map = parser.buildTeamsMap(teamsJson);
var out = '// GENERATED by tools/gen_teams.js from tools/worldcup.teams.json - do not edit.\n' +
          'module.exports = ' + JSON.stringify(map, null, 2) + ';\n';
fs.writeFileSync(path.join(__dirname, '..', 'src', 'pkjs', 'teams.js'), out);
console.log('wrote src/pkjs/teams.js with ' + Object.keys(map).length + ' names');
