#!/usr/bin/env python3
"""Generate 1-bit flag resources for the 48 qualified teams.

Downloads each flag from flagcdn.com, resizes to 20x12, Floyd-Steinberg
dithers to 1-bit, and writes:
  - resources/images/flag_<FIFA>.png   (48 files)
  - src/c/flag_resources.h             (FIFA code -> resource ID table)
  - package.json                       (pebble.resources.media rewritten)

Run manually from the repo root; outputs are committed:
    python3 tools/gen_flags.py
Requires Pillow: pip3 install Pillow
"""
import io
import json
import os
import urllib.request

from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FLAG_W, FLAG_H = 20, 12

FIFA_TO_ISO = {
    'ALG': 'dz', 'ARG': 'ar', 'AUS': 'au', 'AUT': 'at', 'BEL': 'be',
    'BIH': 'ba', 'BRA': 'br', 'CAN': 'ca', 'CIV': 'ci', 'COD': 'cd',
    'COL': 'co', 'CPV': 'cv', 'CRO': 'hr', 'CUW': 'cw', 'CZE': 'cz',
    'ECU': 'ec', 'EGY': 'eg', 'ENG': 'gb-eng', 'ESP': 'es', 'FRA': 'fr',
    'GER': 'de', 'GHA': 'gh', 'HAI': 'ht', 'IRN': 'ir', 'IRQ': 'iq',
    'JOR': 'jo', 'JPN': 'jp', 'KOR': 'kr', 'KSA': 'sa', 'MAR': 'ma',
    'MEX': 'mx', 'NED': 'nl', 'NOR': 'no', 'NZL': 'nz', 'PAN': 'pa',
    'PAR': 'py', 'POR': 'pt', 'QAT': 'qa', 'RSA': 'za', 'SCO': 'gb-sct',
    'SEN': 'sn', 'SUI': 'ch', 'SWE': 'se', 'TUN': 'tn', 'TUR': 'tr',
    'URU': 'uy', 'USA': 'us', 'UZB': 'uz',
}

STATIC_MEDIA = [
    {"type": "bitmap", "name": "FLAG_TBD", "file": "images/flag_TBD.png"},
    {"type": "bitmap", "name": "IMAGE_BALL_SMALL", "file": "images/ball_small.png"},
    {"type": "bitmap", "name": "IMAGE_BALL_LARGE", "file": "images/ball_large.png"},
    {"type": "bitmap", "name": "IMAGE_TROPHY", "file": "images/trophy.png"},
    {"type": "bitmap", "name": "IMAGE_BT_OFF", "file": "images/bt_off.png"},
]


def main():
    with open(os.path.join(REPO, 'tools', 'worldcup.teams.json')) as f:
        teams = json.load(f)
    codes = sorted(t['fifa_code'] for t in teams)
    assert len(codes) == 48, 'expected 48 teams, got %d' % len(codes)
    missing = [c for c in codes if c not in FIFA_TO_ISO]
    assert not missing, 'no ISO mapping for %s' % missing

    img_dir = os.path.join(REPO, 'resources', 'images')
    os.makedirs(img_dir, exist_ok=True)
    for code in codes:
        url = 'https://flagcdn.com/w40/%s.png' % FIFA_TO_ISO[code]
        with urllib.request.urlopen(url, timeout=30) as r:
            data = r.read()
        img = Image.open(io.BytesIO(data)).convert('RGB').convert('L')
        img = img.resize((FLAG_W, FLAG_H), Image.LANCZOS)
        img = img.convert('1')  # Floyd-Steinberg dither is Pillow's default
        img.save(os.path.join(img_dir, 'flag_%s.png' % code))
        print('wrote flag_%s.png' % code)

    lines = [
        '// GENERATED by tools/gen_flags.py - do not edit.',
        '#pragma once',
        '#include <pebble.h>',
        '#include <string.h>',
        '',
        'typedef struct { const char *code; uint32_t resource_id; } FlagEntry;',
        '',
        'static const FlagEntry FLAG_TABLE[] = {',
    ]
    for code in codes:
        lines.append('  { "%s", RESOURCE_ID_FLAG_%s },' % (code, code))
    lines += [
        '};',
        '',
        'static inline uint32_t flag_resource_for_code(const char *code) {',
        '  for (size_t i = 0; i < sizeof(FLAG_TABLE) / sizeof(FLAG_TABLE[0]); i++) {',
        '    if (strncmp(code, FLAG_TABLE[i].code, 3) == 0) return FLAG_TABLE[i].resource_id;',
        '  }',
        '  return RESOURCE_ID_FLAG_TBD;',
        '}',
        '',
    ]
    with open(os.path.join(REPO, 'src', 'c', 'flag_resources.h'), 'w') as f:
        f.write('\n'.join(lines))
    print('wrote src/c/flag_resources.h')

    pkg_path = os.path.join(REPO, 'package.json')
    with open(pkg_path) as f:
        pkg = json.load(f)
    media = [{"type": "bitmap", "name": "FLAG_%s" % c, "file": "images/flag_%s.png" % c}
             for c in codes]
    pkg['pebble']['resources']['media'] = media + STATIC_MEDIA
    with open(pkg_path, 'w') as f:
        json.dump(pkg, f, indent=2)
        f.write('\n')
    print('updated package.json with %d media entries' % (len(media) + len(STATIC_MEDIA)))


main()
